### ISSUE TITLE
Separate pages for game versions

### ISSUE THREAD

**Issue by roncli** [leonard-thieu/toofz-necrodancer#22]
On http://toofz.com/p/76561197996696153/roncli, there are a whole bunch of tables, and Classic, which is kind of irrelevant now, is listed first..  I think it would be a good idea to separate game versions - Classic and Amplified - into their own pages.

**Comment by leonard-thieu** [comment]
Sounds good.

How would it look like? How would navigation work?

**Comment by roncli** [comment]
When you land on a user page, below the person's name, you could have either another navbar or a dropdown, or something like that, with options for Classic and Amplified.  It should default to Amplified for sure. :)

**Comment by leonard-thieu** [comment]
Okay, did you want to put in a PR for this?

**Comment by roncli** [comment]
It might be a bit before I can attempt that, it's CoNDOR season after all.
:)
